♻️ 코드 수정 : deploy.yml 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,16 +19,21 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
-        with:
-          java-version: '17'
-          distribution: 'corretto'
+      - name: List all project files
+        run: ls -R
 
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
         working-directory: LearnsMate
         shell: bash
+
+      - name: Verify gradlew exists
+        run: |
+          if [ ! -f "gradlew" ]; then
+            echo "gradlew not found!"
+            exit 1
+          fi
+        working-directory: LearnsMate
 
       - name: Build with Gradle
         run: ./gradlew clean build -x test
